# Generated by Django 4.2.6 on 2023-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='address',
            field=models.TextField(max_length=800),
        ),
    ]
